version: "3"
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 10s
        timeout: 10s
        retries: 5
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
  webapp:
    build: .
    ports:
      - "8888:8888"
    depends_on: 
      mysql:
        condition: service_healthy
    volumes:
      - ./files:/opt/rtb/files:rw
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
      - SQL_DIALECT=mysql
      - SQL_HOST=rootthebox-mysql-1
      - SQL_DATABASE=rootthebox
      - SQL_PORT=3306
      - SQL_USER=root
      - SQL_PASSWORD=mysecretpassword
