version: "3"

services:
  mysql:
    restart: always
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 30s
        timeout: 30s
        retries: 5
    networks:
      - rtb_network
  memcached:
    restart: always
    image: memcached:latest
    ports:
      - "11211:11211"
    networks:
      - rtb_network
  webapp:
    restart: always
    build: .
    ports:
      - "8888:8888"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./files:/opt/rtb/files:rw
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
      - SQL_DIALECT=mysql
      - SQL_HOST=rootthebox-mysql-1
      - SQL_DATABASE=rootthebox
      - SQL_PORT=3306
      - SQL_USER=root
      - SQL_PASSWORD=mysecretpassword
    networks:
      - rtb_network
  nginx:
    restart: always
    image: nginx:1.26.2-alpine
    ports:
      - 8089:80
    volumes:
      - ./static:/usr/share/nginx/html/static
      - ./static:/opt/rootthebox/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - rtb_network

networks:
  rtb_network:
    driver: bridge